### PR TITLE
mmdbctl structured like ipinfo/cli to use as subcommand in cli

### PR DESCRIPTION
**Pull request by awaismslm**
In this PR, I have restructured the `mmdbctl` repo like `ipinfo/cli` repo. So we can use the mmdbctl's code in `ipinfo/cli` for subcommand `mmdbctl`.

I have moved all the core business logic to `mmdbctl/lib`.

### CODE REVIEW

**Review by UmanShahzad — COMMENTED** [review]
Alright at a surface level looks good to me. Can you double-triple check that with the new binary produced from this, that all commands, with all flags, are all working perfectly?

**Comment by awaismslm** [comment]
> Alright at a surface level looks good to me. Can you double-triple check that with the new binary produced from this, that all commands, with all flags, are all working perfectly?

Already on it. I'll let you know.

**Comment by awaismslm** [comment]
@UmanShahzad I have tested the sub-commands and flags thoroughly. All is working well. We can merge the branch.

**Review by UmanShahzad — APPROVED** [review]
Let's go for this and use it in the ipinfo cli itself now. We wont launch this as a new version until the ipinfo CLI side is working perfectly too with this.

**Pull request merged**
